### ISSUE TITLE
CodingError: Could not find any of G#,Ab in key D

### ISSUE THREAD

**Issue by snapdragon** [DavidCEllis/SightreadingPractice#16]
It may be down to the accidentals in music_theory/keys.js. Perhaps 'G' should be 'G#'?

  D: new MusicKey(
    "D",
    ["D", "E", "F#", "G", "A", "B", "C#"],
    ["Eb", "F", "G#", "A#", "C"] // 'G' changed to 'G#'
  ),

**Comment by DavidCEllis** [comment]
Ah yeah looks like I messed that up.

**Comment by DavidCEllis** [comment]
Ok, it'll be fixed when I finish testing everything works as I update dependencies. Thanks for pointing this out.
